#!/usr/bin/bash
NAME=$(jq -r '.name' data.json)
HEIGHT=$(jq -r '.height' data.json)
WEIGHT=$(jq -r '.weight' data.json)
TYPE=$(jq -r '.types[0].type.name' data.json)
HEIGHT_METERS=$(awk "BEGIN {printf \"%.1f\", $HEIGHT / 10}")
WEIGHT_KG=$(awk "BEGIN {printf \"%.0f\", $WEIGHT / 10}")
echo "$NAME is of type $TYPE, weighs ${WEIGHT_KG}kg, and is ${HEIGHT_METERS}m tall."
