#!/usr/bin/bash
NAME=$(jq -r '.name' data.json)
HEIGHT=$(jq -r '.height' data.json)
WEIGHT=$(jq -r '.weight' data.json)
TYPE=$(jq -r '.types[0].type.name' data.json)

FORMATTED_HEIGHT=$(awk "BEGIN {printf \"%.1f\", $HEIGHT / 10}")
FORMATTED_WEIGHT=$(awk "BEGIN {printf \"%.0f\", $WEIGHT / 10}")

CAPITALIZED_TYPE=$(echo "$TYPE" | sed 's/.*/\u&/')

# "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
echo "$NAME is of type $CAPITALIZED_TYPE, weighs ${FORMATTED_WEIGHT}kg, and is ${FORMATTED_HEIGHT}m tall."
