#!/bin/bash
DIR_NAME="pokemon_data"
CSV_FILE="pokemon_report.csv"

#loop all files in the directory
if [ -d "${DIR_NAME}" ]; then
    echo "Directory ${DIR_NAME} already exists."
else
    bash batchProcessing-0x02.sh
    echo "Directory ${DIR_NAME} created."
fi

#create csv file
if [ -f "${CSV_FILE}" ]; then
    echo "CSV file ${CSV_FILE} already exists. Overwriting..."
    rm "${CSV_FILE}"
else
    echo "Creating CSV file ${CSV_FILE}..."
    touch "${CSV_FILE}"
fi

echo "Name,Height (m),Weight (kg)" > ${CSV_FILE}

for FILE in ${DIR_NAME}/*.json; do
    NAME=$(jq -r '.name' "${FILE}")
    HEIGHT=$(jq -r '.height' "${FILE}")
    WEIGHT=$(jq -r '.weight' "${FILE}")
    NAME_UPPER=$(echo "$NAME" | sed 's/.*/\u&/')
    FORMATTED_HEIGHT=$(awk "BEGIN {printf \"%.1f\", $HEIGHT / 10}")
    FORMATTED_WEIGHT=$(awk "BEGIN {printf \"%.0f\", $WEIGHT / 10}")
    echo "${NAME_UPPER},${FORMATTED_HEIGHT},${FORMATTED_WEIGHT}" >> ${CSV_FILE}
done

AVERAGE_HEIGHT=$(awk -F, 'NR > 1 {sum += $2} END {print sum/(NR-1)}' ${CSV_FILE})
AVERAGE_WEIGHT=$(awk -F, 'NR > 1 {sum += $3} END {print sum/(NR-1)}' ${CSV_FILE})
echo "CSV Report generated at: ${CSV_FILE}"
cat "$CSV_FILE"


echo "Average Height: ${AVERAGE_HEIGHT}m"
echo "Average Weight: ${AVERAGE_WEIGHT}kg"